// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://hgcbxwttbwwschlgiigj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnY2J4d3R0Ynd3c2NobGdpaWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDgzOTgsImV4cCI6MjA3MDMyNDM5OH0.8AD_LuEhx3NkG6upFTb5SCDTAS4k0DcV-SxdmUu8AvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});